include:
  - board: nice_nano_v2
    shield: pinky3_left
  - board: nice_nano_v2
    shield: pinky3_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: pinky3_dongle
